version: "3.0"
services:
  node-app:
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aldi
      - MONGO_INITDB_ROOT_PASSWORD=aldi
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
volumes:
  mongo-db: